# states
GROUND = ("AU SOL", 0X00)
CHANG_ALT = ("CHANGEMENT D'ALTITUDE", 0X01)
CRUISING = ("VOL EN CROISIÈRE", 0X02)
FREE_FALL = ("ALERT!\nON TOMBE",0X03)
# Max values
MAX_ALT = 40000 # Feet
MAX_CLIMB = 800 # m/min
MAX_ANGLE = 16  # Degrees
# Resolutions
ALT_RES = 1 # Feet
CLIMB_RES = 0.1 # m/min
ANGLE_RES = 0.1 # deg
# Arinc429 labels
LABEL_ALT = ("LABEL ALT",0o1)
LABEL_STATE = ("LABEL_STATE",0o1)
LABEL_CLB_R = ("LABEL_CLB_R",0o2)
LABEL_ANGLE = ("LABEL_ANGLE",0o3)
# SSM - BCD
POS = [0, 0]
NCD = [0, 1]
TEST = [1, 0]
NEG = [1, 1]
